name: Deploying a terraform state

on:
  push:
    branches:
      [main]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Run PHPUnit
        uses: php-actions/phpunit@v4  
        with:
          version: 9.6
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text


  deploy:
    runs-on: ubuntu-latest
    needs: phpunit
    
    if: ${{ success() }}

    env:
      aws_region: us-east-1
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          aws-access-key-id: ${{ env.aws_access_key_id }}
          aws-secret-access-key: ${{ env.aws_secret_access_key }}
          aws-session-token: ${{ env.aws_session_token }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Deploying terraform state
        working-directory: ./terraform
        run: | 
          terraform init
          terraform plan
          terraform apply -auto-approve
          
